// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQic_QE5kAv7PRJvX7TBkpNUr9NGOVi38',
    appId: '1:685796818981:web:7e57d694b981a329c67fcc',
    messagingSenderId: '685796818981',
    projectId: 'easy-chating-8ab11',
    authDomain: 'easy-chating-8ab11.firebaseapp.com',
    storageBucket: 'easy-chating-8ab11.appspot.com',
    measurementId: 'G-Q804TXK7GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jOLY5a0URig2r5Anb3OdsAQHmeJXlm8',
    appId: '1:685796818981:android:319309452db02e09c67fcc',
    messagingSenderId: '685796818981',
    projectId: 'easy-chating-8ab11',
    storageBucket: 'easy-chating-8ab11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR0l77aY-tmX-oaGzN1C1eabhxtRFKWsA',
    appId: '1:685796818981:ios:9a53d1840ad87923c67fcc',
    messagingSenderId: '685796818981',
    projectId: 'easy-chating-8ab11',
    storageBucket: 'easy-chating-8ab11.appspot.com',
    iosClientId: '685796818981-5r0cirer11h5ar4tmhvgil8j6rs956sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.easychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR0l77aY-tmX-oaGzN1C1eabhxtRFKWsA',
    appId: '1:685796818981:ios:df9afe1fb7016afdc67fcc',
    messagingSenderId: '685796818981',
    projectId: 'easy-chating-8ab11',
    storageBucket: 'easy-chating-8ab11.appspot.com',
    iosClientId: '685796818981-5vefhnqjag2i0dart97cnotqmvcbfore.apps.googleusercontent.com',
    iosBundleId: 'com.example.easychat.RunnerTests',
  );
}
